include $(BUGNES_ROOT)/build/head.mk

CFLAGS+=-I./include -I$(BUGNES_ROOT)/include

SOURCES = addr.c core.c disas.c excepthooks.c memhooks.c opcodes.c sfot.c
SOURCES_PATH = src
COMPILE_PATH = obj

STATIC_LIBRARY := libsfot.a

include $(BUGNES_ROOT)/build/tail.mk
